--- 
before_script: 
  - "mysql -e 'create database test;' -u root"
env: 
  - DJANGO_VERSION=1.1.3
  - DJANGO_VERSION=1.11.27
install: 
  - "pip install -q Django==$DJANGO_VERSION"
  - "python setup.py -q install"
language: python
python: 
  - "3.6"
script: 
  - "python manage.py test"
services: 
  - mysql
