--- 
language: python
env: 
  global: 
    - PYTHON_PIP_VERSION=19.2.3
    - "DJANGO_VERSION=\">=1.10,<1.11\""
python:
  - 2.7
  - 3.6
after_failure: 
  - "dmesg | tail -n 100"
before_install: 
  - mysql -e 'create database test;'
  - "pip install \"pip==${PYTHON_PIP_VERSION}\""
install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
script: 
  - python manage.py test
