language: python # => 1
    python: # => 2
      - "2.7"
      - "3.6"
    services: # => 3
      - mysql
    env:
      - DJANGO_VERSION=2.1.13
      - DJANGO_VERSION=2.2.6
    install: # => 5
      - pip install -q Django==$DJANGO_VERSION
      - python setup.py -q install
    before_script: # => 6
      - mysql -e 'create database test;' -u root
    script: # => 7
      - python manage.py test
