--- 
language: python
env: 
  global: 
    - PYTHON_PIP_VERSION=19.2.3
    - DJANGO_VERSION=1.1.3
    - DJANGO_VERSION=1.11.27
python:
  - 2.7
  - 3.6
after_failure: 
  - "dmesg | tail -n 100"
before_install: 
  - "pip install \"pip==${PYTHON_PIP_VERSION}\""
install:
  - pip install django==$DJANGO_VERSION --quiet
script: 
  - python manage.py
