--- 
before_script: 
  - "mysql -e 'create database test;' -u root"
env: 
  - DJANGO_VERSION=2.1.13
  - DJANGO_VERSION=2.2.6
install: 
  - "pip install -q Django==$DJANGO_VERSION"
  - "python setup.py -q install"
language: python
python: 
  - "2.7"
  - "3.6"
script: 
  - "python manage.py test"
services: 
  - mysql
